DefaultContentLanguage = "id"
baseURL = "https://rumahsakha.netlify.com/"
disableLanguages = []
disqusShortname = "educenter"
paginate = "6"
summaryLength = "10"
theme = "educenter-hugo"
title = "Rumah Sakha | Rumah Anak Cerdas!"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Home"
kelas = "Class"
languageCode = "en-us"
languageName = "English"
weight = 2

[[languages.en.menu.footer]]

URL = "teacher"
name = "teacher"
URL = "notice"
name = "notice"
URL = "event"
name = "event"
URL = "scholarship"
name = "scholarship"
URL = "research"
name = "research"

[[languages.en.menu.main]]

URL = "about"
name = "About"
weight = 1
URL = "course"
name = "Class"
weight = 2
hasChildren = true
name = "Pages"
weight = 3
URL = "teacher"
name = "teacher"
parent = "Pages"
URL = "notice"
name = "notice"
parent = "Pages"
URL = "event"
name = "event"
parent = "Pages"
URL = "research"
name = "GerakanBerbagi"
parent = "Pages"
URL = "blog"
name = "blog"
weight = 4
URL = "contact"
name = "Contact"
weight = 5

[Languages.id]
About = "Tentang"
contentDir = "content/indonesia"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Beranda"
languageCode = "id-id"
languageName = "Indonesia"
weight = 1

[[languages.id.menu.footer]]

URL = "teacher"
name = "Guru"
URL = "notice"
name = "Catatan"
URL = "event"
name = "Acara"
URL = "scholarship"
name = "scholarship"
URL = "research"
name = "GerakanBerbagi"

[[languages.id.menu.main]]

URL = "about"
name = "Tentang"
weight = 1
URL = "course"
name = "Kelas"
weight = 2
hasChildren = true
name = "Pages"
weight = 3
URL = "teacher"
name = "Guru dan Tim"
parent = "Pages"
URL = "notice"
name = "Catatan"
parent = "Pages"
URL = "event"
name = "Acara"
parent = "Pages"
URL = "research"
name = "GerakanBerbagi"
parent = "Pages"
URL = "blog"
name = "Blog"
weight = 4
URL = "contact"
name = "Kontak"
weight = 5


[params]
address = "Muara Enim"
author = "Riskal Ahyat"
contact_form_action = "https://formspree.io/mqklvnwq"
description = "Rumah Sakha, Rumah Anak Bahagia, Generasi Berkah"
email = "kontak@rumahsakha.my.id"
google_analitycs_id = ""
logo = "images/logo.png"
mobile = "+62812 7813 3632"
pendaftaran_form = ""
top_header = true
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[params.subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
